import { PositionCode } from "@/types";

export const APP_NAME = "16-0";

export const COLORS = {
  // Primary palette
  plum: "#0033A0",       // primary blue
  plumDark: "#00183F",   // dark navy
  plumLight: "#D9D9D9",  // neutral light

  // Neutral aliases mapped to palette
  sage: "#D9D9D9",
  ivory: "#D9D9D9",
  sand: "#D9D9D9",
  rose: "#D9D9D9",
  sageDark: "#00183F",
  pitchGreen: "#0033A0",
  pitchGreenDark: "#00183F",
} as const;

export const POSITION_LABELS_MAP: Record<string, Record<PositionCode, string>> = {
  en: {
    GOL: "GK",
    LD: "RB",
    ZAG: "CB",
    LE: "LB",
    VOL: "CDM",
    MC: "CM",
    MEI: "CAM",
    ME: "LM",
    MD: "RM",
    PE: "LW",
    PD: "RW",
    CA: "ST",
  },
  pt: {
    GOL: "GOL",
    ZAG: "ZAG",
    LD: "LD",
    LE: "LE",
    VOL: "VOL",
    MC: "MC",
    ME: "ME",
    MD: "MD",
    MEI: "MEI",
    CA: "CA",
    PD: "PD",
    PE: "PE",
  },
};

export function getPositionLabel(pos: PositionCode, lang: string = "en") {
  return (POSITION_LABELS_MAP[lang] && POSITION_LABELS_MAP[lang][pos]) || pos;
}

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    start: "Start",
    football_sim: "Football Simulation",
    tagline: "Build your dream squad. Conquer Europe.",
    choose_position: "Choose a position:",
    ovr: "OVR",
    cancel: "Cancel",
    confirm: "Confirm",
    squad_progress: "Squad Progress",
    empty: "Empty",
    your_team: "Your Team",
    build_your_squad: "Build Your Squad",
    round_label: "Round",
    squad_complete: "Squad Complete!",
    starting_tournament: "Starting tournament...",
    choose_formation_title: "Choose Your Formation",
    choose_formation_sub: "Select a formation to build your squad around",
    select_formation_above: "Select a formation above",
    begin_draft: "Begin Draft",
    league_title: "Champions League",
    league_phase: "League Phase",
    your_matches: "Your Matches",
    standings: "Standings",
    qualified_label: "Qualified (Top 16)",
    eliminated_label: "Eliminated",
    qualified_title: "Qualified!",
    you_finished: "You finished",
    advance_to_knockout: "and advance to the knockout rounds!",
    did_not_qualify: "and did not qualify for the knockout rounds.",
    continue_to_knockout: "Continue to Knockout →",
    view_results: "View Results",
    advanced: "Advanced ✓",
    eliminated: "Eliminated ✗",
    vs: "vs",
    match: "Match",
    first_leg: "1st Leg",
    second_leg: "2nd Leg",
    aggregate: "Aggregate",
    champion_label: "CHAMPION",
    result_champion_text: "You built an unstoppable squad and conquered Europe!",
    result_eliminated_text: "Your journey ends here, but legends never die.",
    record_label: "Record (W-D-L)",
    goals_scored: "Goals Scored",
    goals_conceded: "Goals Conceded",
    play_again: "Play Again",
    knockout_stage: "Knockout Stage",
    win_or_go_home: "Win or go home. Every match counts.",
    champion_exclaim: "CHAMPION!",
    you_conquered: "You conquered Europe!",
    journey_over: "Journey Over",
    valiant_effort: "A valiant effort. Better luck next time.",
    see_results: "See Results",
  },
  pt: {
    start: "Iniciar",
    football_sim: "Simulação de Futebol",
    tagline: "Monte seu time dos sonhos. Conquiste a Europa.",
    choose_position: "Escolha uma posição:",
    ovr: "OVR",
    cancel: "Cancelar",
    confirm: "Confirmar",
    squad_progress: "Progresso do Elenco",
    empty: "Vazio",
    your_team: "Seu Time",
    build_your_squad: "Monte seu Elenco",
    round_label: "Rodada",
    squad_complete: "Elenco Completo!",
    starting_tournament: "Iniciando o torneio...",
    choose_formation_title: "Escolha sua Formação",
    choose_formation_sub: "Selecione uma formação para montar seu elenco",
    select_formation_above: "Selecione uma formação acima",
    begin_draft: "Iniciar Draft",
    league_title: "Liga dos Campeões",
    league_phase: "Fase de Grupo",
    your_matches: "Seus Jogos",
    standings: "Classificação",
    qualified_label: "Classificado (Top 16)",
    eliminated_label: "Eliminado",
    qualified_title: "Classificado!",
    you_finished: "Você terminou em",
    advance_to_knockout: "e avançou para as fases eliminatórias!",
    did_not_qualify: "e não se classificou para as fases eliminatórias.",
    continue_to_knockout: "Continuar para Eliminatórias →",
    view_results: "Ver Resultados",
    advanced: "Classificado ✓",
    eliminated: "Eliminado ✗",
    vs: "vs",
    match: "Partida",
    first_leg: "1º Jogo",
    second_leg: "2º Jogo",
    aggregate: "Agregado",
    champion_label: "CAMPEÃO",
    result_champion_text: "Você montou um elenco imbatível e conquistou a Europa!",
    result_eliminated_text: "Sua jornada termina aqui, mas lendas nunca morrem.",
    record_label: "Recorde (V-E-D)",
    goals_scored: "Gols Marcados",
    goals_conceded: "Gols Sofridos",
    play_again: "Jogar Novamente",
    knockout_stage: "Fase Eliminatória",
    win_or_go_home: "Quem vence avança. Todo jogo conta.",
    champion_exclaim: "CAMPEÃO!",
    you_conquered: "Você conquistou a Europa!",
    journey_over: "Jornada Encerrada",
    valiant_effort: "Um esforço valoroso. Boa sorte na próxima vez.",
    see_results: "Ver Resultados",
  },
};

export const POSITION_COLORS: Record<PositionCode, string> = {
  GOL: "#f59e0b",
  LD: "#3b82f6",
  ZAG: "#3b82f6",
  LE: "#3b82f6",
  VOL: "#10b981",
  MC: "#10b981",
  MEI: "#8b5cf6",
  ME: "#10b981",
  MD: "#10b981",
  PE: "#ef4444",
  PD: "#ef4444",
  CA: "#ef4444",
};
